version: "2"
services:
  migrations:
    environment:
      - NODE_ENV=test
      - PORT=3000
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DB_URL=postgres://username:Dummy123@postgres/<%= name %>-store
      - DB_URL_TEST=postgres://username:Dummy123@postgres/<%= name %>-store
    command: yarn db:migrate

  <%= name %>:
    environment:
      - NODE_ENV=test
      - PORT=3000
      - AWS_DEFAULT_REGION=ap-southeast-1
      - DB_URL=postgres://username:Dummy123@postgres/<%= name %>-store
      - DB_URL_TEST=postgres://username:Dummy123@postgres/<%= name %>-store
    command: yarn test
